[package]
name = "fidl"
version = "0.1.0"
license = "BSD-3-Clause"
authors = ["Raph Levien <raph@google.com>", "Taylor Cramer <cramertj@google.com>"]
description = "Library and runtime for Rust fidl bindings"
repository = "https://fuchsia.googlesource.com/fidl/"

[dependencies]
byteorder = "0.5.3"
magenta = { path = "../../../../rust/magenta-rs" }
futures = "0.1"
tokio-core = "0.1.9"
tokio-fuchsia = { path = "../../../../rust/tokio-fuchsia", version = "0.1" }
